server:
  port: 2222
spring:
  application:
    name: VueBlogNeteaseCloudMusicApi
  redis:
    url: 127.0.0.1
    port: 6379
    database: 0
    password: ''
    lettuce:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 2
    client-type: lettuce

api:
  server:
    url: 'http://localhost:3000/'
    serverUrl: ''
    email: ''
    passWord: ''
    splitCount: 10
    defaultMusicLevel: 'lossless'
    # nanos、millis、minutes、seconds、hours、days
    redisTtlType: HOURS
    redisTtl: 1
    redisMusicInfoCachePrefix: 'vueblog:music:list:'
    redisLyricCachePrefix: 'vueblog:lyric:list:'
