server:
  port: 2222
spring:
  application:
    name: VueBlogNeteaseCloudMusicApi
api:
  server:
    url: 'http://localhost:3000/'
    serverUrl: ''
    email: ''
    passWord: ''
    splitCount: 10
    defaultMusicLevel: 'lossless'
